# Generated by Django 2.0 on 2018-01-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='creator',
            field=models.IntegerField(default=0),
        ),
    ]
