# Generated by Django 2.0 on 2018-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
