# Generated by Django 2.0 on 2018-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='name',
            field=models.CharField(default='', max_length=48),
        ),
        migrations.AlterModelTable(
            name='status_user',
            table='status_user',
        ),
    ]
