# Generated by Django 2.0 on 2018-01-24 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180123_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='operation_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('operate_time', models.DateTimeField(blank=True, null=True)),
                ('operate_type', models.CharField(default='', max_length=2048)),
                ('old_data', models.CharField(default='', max_length=2048)),
                ('new_data', models.CharField(default='', max_length=2048)),
                ('remark', models.CharField(default='', max_length=2048)),
            ],
            options={
                'db_table': 'operation_note',
            },
        ),
        migrations.AddField(
            model_name='institutions',
            name='edit_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='devices',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='funcmodule',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status_module',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status_user',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
    ]
