# Generated by Django 2.0 on 2018-02-05 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_devices_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(default='', max_length=32)),
                ('platform_trade_no', models.CharField(default='', max_length=64)),
                ('refund_trade_no', models.CharField(blank=True, max_length=32, null=True)),
                ('refund_platform_trade_no', models.CharField(blank=True, max_length=64, null=True)),
                ('merchant_no', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('payed', models.BooleanField(default=False)),
                ('communication_succeeded', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('order_tpye', models.BooleanField(default=False)),
                ('customer1', models.CharField(default='', max_length=32)),
                ('customer2', models.CharField(default='', max_length=256)),
                ('device', models.IntegerField(blank=True, null=True)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('payment_channel', models.CharField(default='', max_length=32)),
                ('initial_amount', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(default=100)),
                ('discounted_amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='CNY', max_length=30)),
                ('description', models.CharField(default='', max_length=256)),
                ('remark', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(default='', max_length=32)),
                ('platform_trade_no', models.CharField(default='', max_length=64)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('payment_channel', models.CharField(default='', max_length=32)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('auxiliary', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(default='', max_length=256)),
                ('account_name', models.CharField(default='', max_length=256)),
                ('period_from', models.DateTimeField(default=datetime.datetime.now)),
                ('period_to', models.DateTimeField(default=datetime.datetime.now)),
                ('succeeded', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='wechat_openId',
        ),
        migrations.AddField(
            model_name='accounts',
            name='alipay_auxiliaryRate',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='accounts',
            name='wechat_auxiliaryRate',
            field=models.IntegerField(default=5),
        ),
    ]
