# Generated by Django 2.0 on 2018-01-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='pipe',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.IntegerField(default=1),
        ),
    ]
