# Generated by Django 2.0 on 2018-01-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180131_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='pipe',
        ),
        migrations.AddField(
            model_name='status',
            name='inst_id',
            field=models.IntegerField(default=0),
        ),
    ]
