# Generated by Django 2.0 on 2018-01-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180131_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcmodule',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
    ]
