# Generated by Django 2.0 on 2018-02-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180131_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='inst_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
