# Generated by Django 2.0 on 2018-02-02 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_devices_inst_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='user_id',
        ),
    ]
