# Generated by Django 2.0 on 2018-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(blank=True, null=True)),
                ('inst_id', models.IntegerField(blank=True, null=True)),
                ('auth_type', models.IntegerField(default=1)),
                ('remark', models.CharField(default='', max_length=48)),
            ],
            options={
                'db_table': 'device_inst',
            },
        ),
    ]
